#com\.j256\.ormlite.* = DEBUG
#com\.j256\.ormlite\.stmt\.mapped\.BaseMappedStatement = DEBUG
#com\.j256\.ormlite\.stmt\.mapped\.MappedCreate = DEBUG
#com\.j256\.ormlite\.stmt\.StatementExecutor = DEBUG